info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
spring:
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: http://git.minstone.com.cn/liuyang/petty-microservice-config.git
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: pettyfer
    password: liuyang19950123
  application:
    name: petty-config
server:
  port: 40152
---
spring:
 profiles:
   active: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30151/eureka