info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
server:
  port: 40154
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30151/eureka
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
spring:
  application:
    name: petty-monitor
  boot:
    admin:
      context-path: /admin