info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
management:
  security:
    enabled: false
endpoints:
  enabled: true
  actuator:
    enabled: true
  shutdown:
    enabled: false
  logfile:
    enabled: true
  env:
    enabled: false
  dump:
    enabled: false
  auditevents:
    enabled: false
spring:
  application:
    name: petty-config-service
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: pettyfer
    password: liuyang19950123
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: http://git.minstone.com.cn/liuyang/petty-microservice-config.git
server:
  port: 40152
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://127.0.0.1:30151/eureka