spring:
  application:
    name: petty-auth-service
server:
  port: 40151
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30151/eureka
petty:
  auth:
    clientId: demoApp
    clientSecret: demoAppSecret
    scope: server