spring:
  application:
    name: petty-auth-service
server:
  port: 40151
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30151/eureka
petty:
  auth:
    clientId: demo
    clientSecret: demoSecret
    scope: application
logging.level.org.springframework.security: DEBUG