spring:
  application:
    name: petty-auth-service
  thymeleaf:
    cache: false
    prefix: classpath:/tepmlates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
server:
  port: 40151
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30151/eureka
petty:
  auth:
    clientId: demo
    clientSecret: demoSecret
    scope: application
logging.level.org.springframework.security: DEBUG